### ISSUE TITLE
ArrayBuffer needs regression tests

### ISSUE THREAD

**Issue by tilmannOSG** [jerryscript-project/jerryscript#1475]
As discussed in #1467, we need to add a set of regression tests to have some basic test coverage of the ArrayBuffer implementation.

**Comment by tilmannOSG** [comment]
@jiangzidong Created this issue so we don't forget about the tests :)

**Comment by jiangzidong** [comment]
yes, it is a good place to ask and discuss test-related questions.

**Comment by jiangzidong** [comment]
yes, it is a good place to ask and discuss test-related questions.

**Comment by jiangzidong** [comment]
@LaszloLango We have 2 test folders: "tests/jerry" and "tests/jjerry-test-suite". What is the difference betweem them?

**Comment by LaszloLango** [comment]
@jiangzidong, good question. :) It is quite legacy, not sure what was the intention of this. I think the jerry-test-suite was designed to use it instead of the official test262 test suite. "tests/jerry" is mostly regression tests. If we fix a bug, the related regression test must be put there. But there are some general tests too in that folder.
