### ISSUE TITLE
Removing jerryscript.h include from jrt.h

### ISSUE THREAD

**Issue by zherczeg** [jerryscript-project/jerryscript#1791]
It was a shock for me to realize that the public API is available everywhere in the project because it is inluded in jrt.h. JerryScript has an opposite design: we have public/internal aliases for many types. E.g. jerry_value_t (public) is the same as ecma_value_t (private), jerry_length_t (public) = ecma_length_t (private), etc.

However, I realized that now certain types are crawling into the internal side from the public side. This dependency should be dropped. I am willing to work on this.

**Comment by akosthekiss** [comment]
I was the one who opposed against something similar in the referenced PR, so I should speak, I guess: OK with me if done consistently.

**Comment by akosthekiss** [comment]
While I've been looking at various parts of the code, I found some of the mentioned public types without private counterpart used internally:

- jerry-core/ecma: `jerry_object_free_callback_t`, `jerry_object_native_info_t`, `jerry_external_handler_t`
- jerry-core/jcontext: `jerry_vm_exec_stop_callback_t`

Hope it helps.

BTW, I've run into two strangely named public types: `jerry_user_context_init_cb`, `jerry_user_context_deinit_cb` (they have `_cb` suffix instead of the common `_t`). It's certainly not nice to use multiple naming schemes in the public API. So, if you're already working on the public/private type aliases, I'd suggest to rename these outlier public types, too.
