### ISSUE TITLE
Supporting ECMAScript 2015

### ISSUE THREAD

**Issue by lemmaa** [jerryscript-project/jerryscript#205]
The General Assembly of Ecma International has announced the approval of ECMA-262 6th edition.
- http://www.infoq.com/news/2015/06/ecmascript-2015-es6
- http://www.ecma-international.org/publications/standards/Ecma-262.htm

Should we need to change our target to support ES6 immediately? or keep going to finish current target first?
Please share your opinion.
Thanks!

**Comment by kenchris** [comment]
I would say at least supporting Promises should be considered, as it is a requirement for most new Web APIs as defined by W3C, WHATWG etc. It is also heavily used by the Generic Sensor API which we would love to support node.js at some point, instead of just web browsers.

Wouldn't supporting "let" instead of just "var", potentially be able to improve memory usage?

**Comment by zherczeg** [comment]
Supporting promises is probably possible at some point.

Supporting let is very challenging but we might try to do it sometimes.. Lots of engine changes will be required, heavy binary size increase, memory consumption increase, performance drop is expected, so the costs might outweight the gain at the end. So this is not a high priority for us at the moment.

**Comment by zherczeg** [comment]
I think it is worth discussing the ""let" problem, because somebody might have a good idea to do it efficiently.

In ES5.1, you can simulate "let" in the following way:

    // this is the same as: let a = f();
    try {
      throw f();
    } catch(a) {
    }

The catch creates a new lexical environment, which only has one binding, the "a" symbol. This symbol shadows the "var a" symbol (if exists). Hence a new object is created and added it to the lexical environment, which consumes memory and makes resolving slower. You cannot really avoid this because:

    function f() {
      var a = 5;
      g = function () { print(a); }
      {
        let a = 6;
        g();
        print(a);
      }
    }

This prints 5 and 6.

The other problem is control flow. Statements such as try, with, and for-in create contexts which needs to be destroyed when these statements are finished. Furthermore break/continue/throw/return statements can also abort these contexts. This is done by context breaker gotos whose are much more costly than normal gotos.

Since try, etc. statements are rare, they don't really slow down Jerry at this moment. However, I would assume that people would use "let" much more frequently than those others which would add a lot of context management and would cause considerable slowdown. Telling people that you have "let" but don't use it does not makes much sense. 

Hence there are two issues needs to be solved:
 - avoid creating extra lexical environments (extra memory for lexical objects, slower resolve)
 - increased context management costs (extra memory for contexts, creating/destroying them frequently lowers perofrmance)

And there is a third: we don't have AST and enough time to do complex code analysis. So the solution must be lightweight and must work with little available information.

Let is know if anybody has a clever idea. Otherwise I don't think it is worth supporting "let".

**Comment by kenchris** [comment]
try/catch might become more popular in ES2017 where async/await are expected for making common promise based code easier to write. This is already in Edge and Chrome (behind flags, I believe)

**Comment by zherczeg** [comment]
Even more interesting example for let:

    function f() {
      var a = [];
      for (var i = 0; i < 5; i++) {
        let x = i;
        a[i] = function() { print(x); }
      }
      for (var i = 0; i < 5; i++)
        a[i]();
    }
    f()

This prints numbers from 0 to 4. Lexical environment magic.

I think the implementation difficulty depends on the standard. Does promises has ES5 implementation? If so, implementing it should not be too hard since no engine rework is needed. Generators require suspending execution which means the call stack needs to be saved (or they need a separate call stack allocator) somewhere. Nesting generators could have some interesting corner cases if the standard allows it. And also the combination of features could be interesting. E.g. with, eval, and function declaration is easy in theory but if you do:

    with (obj) eval("res = function (){ return g; }");

Doing that properly is challenging. Mix this with declaring generators.

Anyway, these could be useful for long term plans. Probably will be challenging but not impossible.

**Comment by kenchris** [comment]
That seems a bit like magic indeed.

Promises were done before ES2015 and originally in the HTML/DOM spec and then moved to JS, so it should not depend on anything else, but they did introduce the notion of micro-tasks though.

http://www.ecma-international.org/ecma-262/7.0/#sec-promise-constructor
https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

I don't think that I have ever seen any examples of nested generators, and eval is pretty much discouraged today :-)

http://www.2ality.com/2015/03/es6-generators.html

**Comment by kenchris** [comment]
By nesting do you mean

```
function* gen1() {
  yield 3;
  yield 2;
  yield 1;
}

function* gen2() { 
  var gen = gen1(); 
  for (var res = gen.next(); !res.done; res = gen.next()) {
    yield res.value;
  } 
}
```
That seems to work in Chrome

```
> var test = gen2();
undefined
> test.next()
Object {value: 3, done: false}
> test.next()
Object {value: 2, done: false}
> test.next()
Object {value: 1, done: false}
> test.next()
Object {value: undefined, done: true}
```

**Comment by zherczeg** [comment]
Yes. Even if it is unlikely that people use such thing if we implement generators we need to support every possible corner case. This is the bulk of the work.

**Comment by kenchris** [comment]
But if this is to serve as the implementation of async/await (without exposing the generator support to devs) would that be the same amount of work?

**Comment by zherczeg** [comment]
Do you mean implement async without generators? That is probably possible. And later extend the implementation to support generators if needed.

**Comment by kenchris** [comment]
Yes, or just the parts of generators (without exposing it) that are needed in order to implement and expose async/await.

I expect that async/await will be enabled by default soon in most browsers and it will probably make promises even more popular, while making async code much easier to write and read.

**Comment by zherczeg** [comment]
function helper() {
      yield 1;
      yield 2;
      yield 3;
    }

    function* gen() { 
      helper();
    }

    var g = gen2(); 
    print(g.next()); // Object { value: undefined, done: true }

It seems this is not working, which is great news, since generators can use the normal call stack when calling other functions. Only their own call frame needs to be allocated in the memory, which simplify heavily the complexity of this task. Is this true?

**Comment by kenchris** [comment]
I would say that is correct, ```YieldExpression :``` is only handled inside http://www.ecma-international.org/ecma-262/6.0/#sec-generator-function-definitions-runtime-semantics-evaluation

yield seems to be only allowed inside generator functions, but then of course in many places of the grammar, like ```return (a == b) ? yield a : ...```.

**Comment by zherczeg** [comment]
Yes, yield is some kind of unary operator with a unique precedence (still much easier than the arrow operator, which requires look-ahead operation in an AST less parser).

Anyway at least we don't need to support cases where a generator calls a native function, and that calls a JS callback function, which yields something. This is a huge simplification. So we just need to allocate a call frame for the generator function _only_, and we can simply suspend the execution at the point of yield. This is quite easy to do in jerry.

So it is likely these two features can be implemented in jerry without much trouble. However it is still a lot of new code, so it definitely takes time.

**Comment by kenchris** [comment]
Yes, that is expected :-) but it would be very nice if you considered it next time you do plannings. Is JerryScript already 100% ES5.1 compliant?

**Comment by zherczeg** [comment]
Yes, except internalization support. (Note: ES6 is not fully backward compatible)

**Comment by brianjjones** [comment]
Hi,

I was curious if there were plans to eventually implement ES6 module support in JerryScript?

**Comment by lygstate** [comment]
I suggest do not implement the full es6 standard， but implement those are not easily or properly to be implement by polyfill or transpiler

**Comment by zherczeg** [comment]
Intel has already started to implement typed arrays. Promises might be the next. So this is underway.

**Comment by martijnthe** [comment]
JFYI, tracking ES6 Promise support separately over here:
https://github.com/jerryscript-project/jerryscript/issues/1675
