### ISSUE TITLE
How to throw an exception in Promise

### ISSUE THREAD

**Issue by LaszloLango** [jerryscript-project/jerryscript#2109]
@jiangzidong the following code snippet is based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

```js
var p1 = new Promise(function(resolve, reject) {
  reject('Failed');
});

p1.then(function(value) {
  console.log(value); // "Success!"
}).catch(function(e) {
  console.log(e); // "oh, no!"
  throw e; // forward the error
}).then(function(){
  console.log('after a catch the chain is restored');
}, function () {
  console.log('Not fired due to the catch');
  throw("This won't be caught");
});
```

My question is that how can I throw an error from a Promise? The code above works with V8 (tested on node.js and chrome console) but not in JerryScript. What is the correct behavior? I'd like to validate the `resolve` and `reject` calls in `then`, but I cannot throw an error from `then`.

**Comment by jiangzidong** [comment]
Now, the correct behavior in jerry engine is "We can't throw an error in a Promise". For nodejs and chrome, it is the runtime who report a **warning** that a promise has unhandled rejection, it is not an error. 

I have an idea to support your validation.
* if you are going to do that in a runtime, for example iot.js, you can use setTimeout(function(){throw "123"}, 0) inside the `resolve`/`reject` calls

* if you need to do that in pure jerry, we need to change the code in both `ecma-promise-object` and `ecma-gc`

1. for each promise object, we need to add an internal prop called `whether it has unhandled rejection`
2. in ecma_promise_trigger_reactions, if the reject-action collection is not empty, then the promise obj has the handler for rejection, then we should set the `whether it has unhandled rejection` as 'false', otherwise `true`
3. in ecma-gc, when a promise obj is about to cleanup, check its `whether it has unhandled rejection`, if `true`, print a warning in the console
