### ISSUE TITLE
The try-catch block is unable to catch the exception?

### ISSUE THREAD

**Issue by YaoHouyou** [jerryscript-project/jerryscript#2905]
The try-catch block is unable to catch the error when I execute the code shows below, but throw  `ERR_REF_COUNT_LIMIT` error .
````
var func = function () {
	foo.prototype = new Array(1, 2, 3);
	function foo() {}
	var f = new foo();
	f.length = f;
	try {
		print("run to try");
		print("Using f will give an error: " + f);
		print("run to 2");
	} catch (e) {
		print("run to catch!")
	}
};
func();
````
The output is:
````
run to try
Error: ERR_REF_COUNT_LIMIT
````

**Comment by LaszloLango** [comment]
`ERR_REF_COUNT_LIMIT` is a fatal error of the engine and not an ECMA262 standard exception, so you cannot catch it.

**Comment by YaoHouyou** [comment]
Do you mean it's a bug of jerry?

**Comment by LaszloLango** [comment]
No, it is not a bug.

**Comment by rerobika** [comment]
@YaoHouyou I agree with @LaszloLango It's not a bug, it is simply a JS call stack overflow. If you remove the `try-catch` block around the `print("Using f will give an error: " + f);` and test it in any browser you will get a RangeError (This is what the catch clause truly catches). Jerry does not manages the call stack size internally, which could lead to `ERR_REF_COUNT_LIMIT` since each call adds an extra reference to the function object/arguments, and in a while, these continuously growing references reaches the limit which terminates the engine.

**Comment by akosthekiss** [comment]
@rerobika jerry-core can be configured to have a recursion limit via the `VM_RECURSION_LIMIT` cmake option (or via the `--vm-recursion-limit` option of build.py). Would that solve the issue and make the engine throw/catch RangeError correctly?

**Comment by rerobika** [comment]
@akosthekiss IMO after a little modification of  `VM_RECURSION_LIMIT` it would be suitable for this problem. This guard prevents only the recursion of the interpreted code blocks but the builtin/native functions calls are not guarded either. I'll open a PR for it.
