### ISSUE TITLE
A bug about String.prototype.charAt

### ISSUE THREAD

**Issue by YuanWangC** [jerryscript-project/jerryscript#3325]
###### JerryScript revision
[7df87b7](https://github.com/jerryscript-project/jerryscript/commit/7df87b7778124af9b0dd309570c33864a67792f7)

###### Build steps
```
python tools/build.py --clean --logging=on --line-info=on --error-messages=o    n --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset
```

###### Test case
```
var NISLFuzzingFunc = {
    var text = 'x';
    var index = Math.random() - 1;
    print( text.charAt(0));
    print( text.charAt(index));
    print( text.charAt(index) === "");
}
NISLFuzzingFunc();
```
###### Execution steps
`jerryscript/build/bin/jerry testcase.js`

###### Output
```
x

true
```
###### Expected behavior
```
x
x
false
```
###### Description:
The variable named `index` is a negative number bigger than -1, and according to Standard ECMA-262 5.1 Edition , the [String.prototype.charAt(pos)](http://www.ecma-international.org/ecma-262/5.1/index.html#sec-15.5.4.4) will call [ToInteger](http://www.ecma-international.org/ecma-262/5.1/index.html#sec-9.4) to process the `pos`. The output of `print( text.charAt(index))` and`print( text.charAt(0))` are the same, which should be 'x'.

**Comment by ossy-szeged** [comment]
Good catch, it is a real bug, but we can simplify the test case:
text.charAt(-0.1) should be "x", because Math.floor(Math.abs(-0.1)) == 0

The bug is in ecma_builtin_string_prototype_char_at_helper function
( jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c )
which doesn't call ToInteger as the spec requires it.
