### ISSUE TITLE
A problem about the regular expression

### ISSUE THREAD

**Issue by NWU-NISL** [jerryscript-project/jerryscript#3844]
When executing the below testcase, `{` is not in the range of the regular expression but JerryScript replaces it. How does jerry replace the letter ```{```? Is this a correct behavior for Jerry?

JerryScript version
[bd1c4d](https://github.com/galpeter/jerryscript/tree/bd1c4df9a608cc7193330944c857ca4f6294b993)

Build platform
Ubuntu 16.04.6 LTS (Linux 4.15.0-55-generic x86_64)

Build steps
python tools/build.py --clean --debug --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset

Testcase

```javascript
var NISLFuzzingFunc = function(a, nislMutatuionParameter1){
	return a.replace(/[#-\w]/g, nislMutatuionParameter1);
};
var NISLParameter0 = '{';
var nislMutatuionArgument0 = false;
var NISLCallingResult = NISLFuzzingFunc(NISLParameter0, nislMutatuionArgument0);
print(NISLCallingResult);
```

Execution steps
./build/bin/jerry testcase.js

Output
false

Expected behavior
{

Conributor:@QuXing9

**Comment by rerobika** [comment]
The following code snippet gives `{` as output in the latest master (https://github.com/jerryscript-project/jerryscript/commit/fe09200d616c4912434e3db6310ed51dd21114fa) but the reported Jerryscript revision not corresponds to the official repository and a _bit_ outdated as well (the commit was 20 days ago). So this problem seems to be resolved to me, closing the issue.
