### ISSUE TITLE
Script function cannot be executed

### ISSUE THREAD

**Issue by X-Crack** [jerryscript-project/jerryscript#4647]
In a self-executing function.

Execution cannot execute the previous function TODO: print(main());

```
var main = function()
    {
        for(var i = 0; i < 10; ++i)
        {
            if(i % 2)
            {
                print("Hello from JS with ext! 1");
            }
            else
            {
                print("Hello from JS with ext! 2");
            }
        }
        return "???????";
    }

    (function ()
    {
        var x = "Hello World";
        print(x);
        print(main());
    }
    )();
```

**Comment by rerobika** [comment]
Hi @X-Crack!

First of all please next time fill the issue template correctly since it currently looks a little bit unprofessional to me. Back to your problem, that's not an engine fault, your problem comes from JS's auto-semicolon insertion.

The code you enclosed is equivalent to the following code below:

```js
var inner = function (){
  var x = "Hello World";
  print(x);
  print(main);
};

var main = function(){
    for(var i = 0; i < 10; ++i)
    {
        if(i % 2)
        {
            print("Hello from JS with ext! 1");
        }
        else
        {
            print("Hello from JS with ext! 2");
        }
    }
    return "???????";
}

main(inner)();
```

That's why you get the TypeError since the returned '?????' is not callable.

Back to the original code: Since the `var main = function () {}` is not terminated by a semicilon therefore after the function's closing `}` is parsed the opening `(` is interpreted as the opeing parenthesis for a callExpression instead of an anonymous function expression definition as you propably wanted.

So the soulition is to simply put a semicolon after `var main = function (){};`
